###
GET http://127.0.0.1:3000/est HTTP/1.1

### donde el 2 es el parámetro
GET http://127.0.0.1:3000/est/2 HTTP/1.1

###
POST http://127.0.0.1:3000/est HTTP/1.1
Content-Type: application/json

{"_id":6,
"carne":"C02256",
"nombre":"Andrea",
"edad":20}

###
PUT http://127.0.0.1:3000/est/5 HTTP/1.1
Content-Type: application/json

{"_id":5,
"carne":"B53454",
"nombre":"Juan",
"edad":22}

###
PATCH http://127.0.0.1:3000/est/5 HTTP/1.1
Content-Type: application/json

{"nombre":"Yobelky", "carne":"C34344"}


###
DELETE http://127.0.0.1:3000/est/5 HTTP/1.1

